README.md
=> 문장을 좀 다듬어 봤습니다.

scrap/kendra_site.py, scrap/page.py, scrap/parser/html.py, scrap/requirements.txt, scrap/serverless.yml
cognito로 로그인 한뒤 쿼리 요청하면 작동 되게 수정 하였습니다
=> support cognito user pool

scrap/kendra_site.py, scrap/scrap.py, scrap/serverless.yml
크롤링을 위한 기본 인프라 구조를 셋팅 했습니다.
sqs 및 DDB 스트림 생성후 람다 트리거로 연결 했으며
각각 트리거 작동 확인 하였습니다.
이제 scrap.py의 operator, worker 함수만 채우면 됩니다.
=> add sqs,ddb stream

frontend/kendra-button-front/src/components/Authenticator.tsx, frontend/kendra-button-front/src/components/SignUp.tsx, frontend/kendra-button-front/src/pages/_app.tsx, frontend/kendra-button-front/src/pages/index.tsx
Fix bugs on Facebook social login
#35 
Resolved #44
=> Fix facebook social login problems

frontend/kendra-button-front/src/components/Content.tsx, frontend/kendra-button-front/src/components/Settings.tsx, frontend/kendra-button-front/src/components/Sidebar.tsx, frontend/kendra-button-front/src/pages/index.tsx
Add grid system, change error messages & alerts
=> Add grid system, change error messages & alerts

frontend/kendra-button-front/src/components/SearchResult.tsx
=> Fix kendra search result 

frontend/kendra-button-front/src/components/Authenticator.tsx, frontend/kendra-button-front/src/components/Confirmation.tsx, frontend/kendra-button-front/src/components/Content.tsx, frontend/kendra-button-front/src/components/EmbedInstruction.tsx, frontend/kendra-button-front/src/components/PageLoader.tsx, frontend/kendra-button-front/src/components/Projects.tsx, frontend/kendra-button-front/src/components/Search.tsx, frontend/kendra-button-front/src/components/SearchResult.tsx, frontend/kendra-button-front/src/components/Sidebar.tsx, frontend/kendra-button-front/src/components/SignIn.tsx, frontend/kendra-button-front/src/components/SignUp.tsx, frontend/kendra-button-front/src/components/SiteMain.tsx, frontend/kendra-button-front/src/components/Title.tsx, frontend/kendra-button-front/src/components/index.tsx, frontend/kendra-button-front/src/layout/index.tsx
you can check on [https://dev.kendra.fun](https://publish.kendra.fun)
(social sign-in is not available. this only available on [admin.kendra.fun](https://admin.kendra.fun))
- Import google fonts(Orbitron, Pacifico)
- Add 'Kendra Button' Title in account related pages & Rearranged signing screen Layout
- Update guide of Embed
- Modify the responsible style of Sidebar Button and Content
- Search component
- Add error validation
- refine codes
=> Implement Responsible View on Page 

amplify.yml, frontend/kendra-button-front/amplfypush.sh, frontend/kendra-button-front/amplify/backend/backend-config.json
- customize [`amplifyPush` script](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#frontend-with-backend) refer to [amplify-console's issue](https://github.com/aws-amplify/amplify-console/issues/206#issuecomment-650689777)
- taking advantage of [environment variables in Amplify Console](https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html)
- remove `S3AndCloudFront` prop in `frontend/kendra-button-front/amplify/backend/backend-config.json` to resolve the error in amplify build
```sh 
{ [Error: ENOENT: no such file or directory, stat '/codebuild/output/src298230785/src/kendra-button/frontend/kendra-button-front/amplify/backend/hosting/S3AndCloudFront']
```
=> Fix Amplify build script in frontend

frontend/kendra-button-front/package.json, frontend/kendra-button-front/src/components/Authenticator.tsx, frontend/kendra-button-front/src/components/Confirmation.tsx, frontend/kendra-button-front/src/components/EmbedInstruction.tsx, frontend/kendra-button-front/src/components/Sidebar.tsx, frontend/kendra-button-front/src/components/SignIn.tsx, frontend/kendra-button-front/src/components/SignUp.tsx, frontend/kendra-button-front/src/components/ViewSource.tsx, frontend/kendra-button-front/src/components/index.tsx, frontend/kendra-button-front/src/pages/index.tsx, frontend/kendra-button-front/yarn.lock
- Change Grid in user signin/signup/confirm
- `EmbedInstruction`: Add more space between sections and change section's title style
- Add `@fortawesome/free-brands-svg-icons` package
- Add "ViewSource" component
- Add Loading screen when user try to social login
=> Change UI and Add Loading screen in Social Sign-in flow

frontend/kendra-button-front/src/components/Authenticator.tsx, frontend/kendra-button-front/src/components/Sidebar.tsx, frontend/kendra-button-front/src/pages/index.tsx
- Fix unnecessary login screen popping up if user is already signed in when refreshing the page
- Fix unintended refresh page when sign out
=> Fix Signin & Signout side effects

frontend/kendra-button-front/src/components/SignIn.tsx
Add formik & Yup to manage forms with validations
=> Modify signin validation

frontend/kendra-button-front/src/components/SiteCreateModal.tsx, frontend/kendra-button-front/src/components/SiteMain.tsx
=> Fix frontend issue1 & issue2

frontend/kendra-button-front/src/components/InputProject.tsx, frontend/kendra-button-front/src/components/Projects.tsx, frontend/kendra-button-front/src/components/SearchResult.tsx, frontend/kendra-button-front/src/components/Settings.tsx, frontend/kendra-button-front/src/components/SiteCreateModal.tsx, frontend/kendra-button-front/src/components/SiteMain.tsx, frontend/kendra-button-front/src/pages/_app.tsx, frontend/kendra-button-front/src/pages/admin.tsx, frontend/kendra-button-service/components/Search.tsx, frontend/kendra-button-service/components/SearchResult.tsx, frontend/kendra-button-service/kendra.js, frontend/kendra-button-service/utils/fetch.ts
Service Refactoring: Change API endpoint & apply amplify logger
- `https://dev.kendra-btns.whatilearened.today/noauth/graphql`
=> Service Refactoring: Change API endpoint & apply amplify logger

frontend/kendra-button-front/src/components/SiteCreateModal.tsx, frontend/kendra-button-front/src/components/SiteMain.tsx
#66 
domain 값 검증후 필드 에러를 보여지지 않는 버그로 추정
=> Resolve issue3: fix Domain and url validation

amplify.yml
=> Hotfix amplify.yml

amplify.yml, frontend/kendra-button-front/amplifypush.sh
Still get `dev` CloudFormation Stack info.
Update latest [amplifyPush script](https://github.com/aws-amplify/amplify-console/blob/master/scripts/amplifyPush.sh) to manual shellscript
=> Modify amplify.yml - 4

cognito/READEME.md
Add cognito userpool backup/restore user guide
=> Add cognito userpool backup/restore user guide

frontend/kendra-button-front/src/components/SiteCreateModal.tsx
- 닫기 버튼의 클릭이벤트 변경
- 사이트 생성 시 duplicate 네트워크 에러가 나올때 exception 처리 안 되어 있던 것 구현.
=> 사이트 생성 모달 및 기능 에러 수정

frontend/kendra-button-front/src/components/SiteCreateModal.tsx
- 닫기 버튼의 클릭이벤트 변경
- 사이트 생성 시 duplicate 네트워크 에러가 나올때 exception 처리 안 되어 있던 것 구현.
=> [Frontend][prod]사이트 생성 모달 및 기능 에러 수정

frontend/kendra-button-front/src/components/CompletePW.tsx
=> [Frontend][dev] Hotfix: Fix tsc

frontend/kendra-button-front/src/components/Search.tsx
- Bugfix: remove unnecessary state "keyword" -> doesn't recognize "keyword" value at first query
=> [Frontend][dev] Remove unnecessary state "keyword"

frontend/kendra-button-front/src/components/Search.tsx
- Revert state "keyword" to fix that changing Search result's word when input value is changing
=> [Frontend][dev] Fix that changing Search result's word

frontend/kendra-button-front/src/components/EmbedInstruction.tsx, frontend/kendra-button-front/src/components/SignIn.tsx, frontend/kendra-button-front/src/components/SiteMain.tsx
- Add Keyboard event: press "enter" key to submit
- press "enter" key in `email` input field -> focus to `password` input field
- Modify wrong instruction message: scrapEndpoint -> domain
=> [Frontend][dev] add keyboard event in signin page and modify embed instruction

frontend/kendra-button-front/src/components/EmbedInstruction.tsx, frontend/kendra-button-front/src/components/Search.tsx, frontend/kendra-button-front/src/components/SignIn.tsx, frontend/kendra-button-front/src/components/SiteMain.tsx, frontend/kendra-button-front/src/pages/index.tsx
Merge from commit & PRs below
- signin page & embed instruction
- #96, ce785b4
- Search Component
- #97, #98, #100
#99
=> [Frontend][prod] merge from `frontend-dev`

frontend/kendra-button-service/components/Search.tsx
Refactor Search Component (sync from dev/prod env)
- Prevent page refresh on Keyword search
- Add Keyboard event: press "enter" key to search
#99
=> [Frontend][service] Refactor Search Component (sync from dev/prod env)

frontend/kendra-button-front/src/components/SiteCreateModal.tsx, frontend/kendra-button-front/src/components/SiteMain.tsx
Add message on site creation & update to notify crawling/indexing time - `dev`
=> [Frontend][dev] Add message on site creation & update to notify crawling/indexing time

frontend/kendra-button-front/src/components/SiteCreateModal.tsx, frontend/kendra-button-front/src/components/SiteMain.tsx
Add message on site creation & update to notify crawling/indexing time - `prod`
resolves #104
=> [Frontend][Prod] Add message on site creation & update to notify crawling/indexing time

frontend/kendra-button-front/src/components/Search.tsx, frontend/kendra-button-front/src/components/SearchResult.tsx
- Reset `keyword` and `inputValue` when select other site
- Implement `pagination` and `multiple highlights` and `button` that opens related url
- merge `master` branch ("prod" env), `service` when bug is not exist
=> [Frontend][dev] Fix frontend dev search

frontend/kendra-button-front/src/components/SearchResult.tsx
- Fix Search result's css(text-transform) All uppercase to none
- merge `master` branch ("prod" env), `service` when bug is not exist
=> [Frontend][dev] Fix Search result's css

frontend/kendra-button-service/components/Search.tsx, frontend/kendra-button-service/components/SearchResult.tsx, frontend/kendra-button-service/graphql/index.ts, frontend/kendra-button-service/package.json, frontend/kendra-button-service/utils/fetch.ts
- related to #108 #110 #111 
- Implement pagination and multiple highlights and button that opens related url
=> [Frontend][service] Fix frontend service query & Modify search component

frontend/kendra-button-service/kendra.js, frontend/kendra-button-service/sample.html
- Import web font & Change kendra-button project embed
- Change style to expand size
Will deploy to [http://button.kendra.fun/sample.html](http://button.kendra.fun/sample.html)
=> [Frontend][service] Change embedding kendra-button project & Change style
